"""new 5.0

Revision ID: 461ea2ea84c2
Revises: f8e141908d29
Create Date: 2022-07-04 12:58:31.617251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '461ea2ea84c2'
down_revision = 'f8e141908d29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_of_policlinic', sa.Column('test_alembic', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_of_policlinic', 'test_alembic')
    # ### end Alembic commands ###
