"""new 2.0

Revision ID: 9cf1cd298bd5
Revises: 97cd054962e7
Create Date: 2022-07-04 12:27:24.195548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cf1cd298bd5'
down_revision = '97cd054962e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
