"""new 6.0

Revision ID: a9dafce61cb8
Revises: 461ea2ea84c2
Create Date: 2022-07-04 12:59:16.463668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9dafce61cb8'
down_revision = '461ea2ea84c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_of_policlinic', 'test_alembic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_of_policlinic', sa.Column('test_alembic', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
