"""new 3.0

Revision ID: b868ff5fbf64
Revises: 9cf1cd298bd5
Create Date: 2022-07-04 12:29:47.847357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b868ff5fbf64'
down_revision = '9cf1cd298bd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_of_policlinic', sa.Column('about', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_of_policlinic', 'about')
    # ### end Alembic commands ###
