"""new 4.0

Revision ID: f8e141908d29
Revises: b868ff5fbf64
Create Date: 2022-07-04 12:57:05.418774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8e141908d29'
down_revision = 'b868ff5fbf64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_of_policlinic', sa.Column('doctor', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_of_policlinic', 'doctor')
    # ### end Alembic commands ###
